### ISSUE TITLE
More items :-)

### ISSUE THREAD

**Issue by jvanhoof** [duracellko/planningpoker4azure#35]
Thanks for fixing the iphone issue, brilliant, can I suggest another couple of edits...

1. When a Scrum Master comes back after closing the browser, you cannot go back in as the SM only a member and so you need to start a new session.
2. When the members choose their estimates, it would be great to have a tick appear on their name on the left as well as the card on the right as you need to try to reconcile this if someone has not provided their estimate.

Thanks again, this is brilliant.

**Comment by duracellko** [comment]
That you very much for your feedback. Especially the seconds point is very good idea.

Regarding first point I see multiple options:
1. User enters team name and scrum master name (the same he/she used to create team) and clicks **Join team**. Then the application would automatically detect it's Scrum Master and reconnect as scrum master. Actually this works already, just not in certain conditions, so it would be improved.
2. User enters team name and scrum master name (the same he/she used to create team) and clicks **Join as Scrum Master**. And user gets connected only when entered correct scrum master name.
3. User enters team name and clicks **Join as Scrum Master** and he/she would be reconnected as Scrum Master.

Which option do you find interesting? The first one may not be intuitive. And third one can be abused (even just from curiosity, what does this button do).

**Comment by jvanhoof** [comment]
1 would be the best if it can be made reliable, what are the conditions that it does not work ? it is what I tried intuatively ... 2 would be the next best option as it still validates the role and you have some limited security around someone highjacking the SM role.

Brilliant, we are using this a lot at the moment as we are in planning and my team are loving it.

Thanks, John

**Comment by duracellko** [comment]
Currently it works the way, when user closes and opens browser (or refresh page, or closes and open tab) and then enters his user name and team name and click **Join**, then the application says that the user already exists and he/she can reconnect as the user. This works also for scrum master.

![image](https://user-images.githubusercontent.com/8131212/79975741-0a59ad00-84ce-11ea-8a73-b6868d486e81.png)

Only if Scrum Master explicitly clicks **Disconnect** from team or the window is closed for more than 30 minutes than he/she is removed from the team. And then cannot reconnect again. And thus team is without Scrum Master.

The solution is that Scrum Master would never get removed from the team. So that he/she can always reconnect. SM can be in status "dormant" to be able to close the whole team after certain time of inactivity, so that the team name can be re-used.

Thank you for your feedback.

**Comment by duracellko** [comment]
Just deployed new version with both points addressed.
Just the icon indicating members waiting for, could be improved. Idea is that it is cloud representing "person is thinking."

**Comment by jvanhoof** [comment]
Could I suggest it is the other way round, no icon when they are thinking and then a tick in the same position when they have voted as well as the card appearing on the right, pop up help text on the icon "member has voted" ... what do you think ? 

I really appreciate these changes, my team found this brilliant last week during our PI planning and it made it all a lot better especially as we were all working from home during this lockdown.

John

**Comment by duracellko** [comment]
I thought that "member not yet estimated" is more important, to see who the team is waiting for. But yes, I can change it.

**Comment by jvanhoof** [comment]
I was thinking about it again and reviewing what you had done, so then thought who has voted is the best way to see it. Thanks again.

**Comment by duracellko** [comment]
The icon has been updated. Now the app shows, who has voted.

**Comment by jvanhoof** [comment]
Brilliant thanks, all good.
